addons:
    apt:
        packages:
            - asciidoc
            - cmake
            - cpanminus
            - dbtoepub
            - docbook-xsl
            - docbook-xsl-ns
            - gcc
            - libperl-dev
            - librecode-dev
            - make
            - perl
            - valgrind
            - xsltproc
            - xz-utils
            - zip
before_install:
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - cpanm App::Docmake Code::TidyAll::Plugin::ClangFormat Code::TidyAll::Plugin::Flake8 Code::TidyAll::Plugin::TestCount File::Find::Object List::Util Path::Tiny Perl::Critic Perl::Tidy Test::Code::TidyAll Test::Differences Test::RunValgrind Test::TrailingSpace Test::Trap
cache:
    directories:
        - $HOME/perl_modules
        - $HOME/tidyall_d
dist: focal
install:
    # Required to avoid default travis "cpanm ." booboo.
    - "true"
language: perl
os: linux
perl:
    - "5.30"
script:
    - "perl -ln -i -E 'print unless /^\\[ClangFormat\\]$/../^$/' fortune-mod/.tidyallrc"
    - "export FORTUNE_TEST_TIDY=1"
    - "perl CI-testing/continuous-integration-testing.pl"
    - "rm -fr B"
